theme: minima
title: SICS-155 Challenge

header_pages:
  - abstract.md
  - dataset.md
  - registration.md
  - submission.md

author:
  name: Simon Mueller
  email: "ag.wintergerst@gmail.com"

minima:
  skin: classic

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc
